### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by amitsri20** [webyog/andriod-dev-task#2]
Hi, I am getting an error when starting the server.
![capture](https://cloud.githubusercontent.com/assets/4771159/19396569/5f7616c4-9261-11e6-88b7-b7b53f7bb79f.PNG)

E:\Node\andriod-dev-task-master\src>npm start

> front-end-challenge@1.0.0 start E:\Node\andriod-dev-task-master\src
> node server.js

Started listening on port 8088
Please point your browser to 127.0.0.1:8088 to see the result. Please note that you'll need to restart the server after making changes.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\tmp\Kratos_access.log'
    at Error (native)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "start"
npm ERR! node v4.6.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! front-end-challenge@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the front-end-challenge@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the front-end-challenge package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs front-end-challenge
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls front-end-challenge
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Node\andriod-dev-task-master\src\npm-debug.log

I have installed Node and NPM.
Please suggest if I am doing anything wrong.

**Comment by nitinrahoria** [comment]
I am having the same issue.. is this fixed?

**Comment by ashwinswy** [comment]
9e6be6b90628d0905252404ace6cd4c98bc0462f

Should be fixed now.
